name: Announce Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  announce-release-discord:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.release.prerelease == false
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Send Discord Notification
        uses: SethCohen/github-releases-to-discord@b96a33520f8ad5e6dcdecee6f1212bdf88b16550 # v1
        with:
          webhook_url: ${{ secrets.DISCORD_ANNOUNCE_WEBHOOK_URL }}
          color: "2105893"
          footer_title: "Obot Release"
          footer_timestamp: true
