name: Announce Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  announce-release-discord:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Send Discord Notification
        uses: SethCohen/github-releases-to-discord@b96a33520f8ad5e6dcdecee6f1212bdf88b16550 # v1
        with:
          webhook_url: ${{ secrets.DISCORD_ANNOUNCE_WEBHOOK_URL }}
          color: "2105893"
          footer_title: "Obot Release"
          footer_timestamp: true
